USE [master]
GO

/****** Object:  Database [Timesheet]    Script Date: 9.06.2022 22:05:19 ******/
CREATE DATABASE [Timesheet]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Timesheet', FILENAME = N'/var/opt/mssql/data/Timesheet.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Timesheet_log', FILENAME = N'/var/opt/mssql/data/Timesheet_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Timesheet].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Timesheet] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Timesheet] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Timesheet] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Timesheet] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Timesheet] SET ARITHABORT OFF 
GO

ALTER DATABASE [Timesheet] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Timesheet] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Timesheet] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Timesheet] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Timesheet] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Timesheet] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Timesheet] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Timesheet] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Timesheet] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Timesheet] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Timesheet] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Timesheet] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Timesheet] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Timesheet] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Timesheet] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Timesheet] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Timesheet] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Timesheet] SET RECOVERY FULL 
GO

ALTER DATABASE [Timesheet] SET  MULTI_USER 
GO

ALTER DATABASE [Timesheet] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Timesheet] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Timesheet] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Timesheet] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Timesheet] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Timesheet] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Timesheet] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Timesheet] SET  READ_WRITE 
GO

